service: pennyboxapp

package:
  exclude:
    - node_modules/dynamodb-localhost/**
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**
    - node_modules/aws-sdk

plugins:
  - serverless-webpack
  - serverless-mocha-plugin
  - serverless-dynamodb-local
  - serverless-offline # This order is important. should be below of dynamodb-local
  # - serverless-dynamodb-autoscaling

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev # prod
  region: us-east-1
  environment:
    SERVICE_NAME: ${self:service}
    DB_PREFIX: ${self:custom.DB_PREFIX}
    COGNITO_POOL_ID: ${self:custom.COGNITO_POOL_ID}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:us-east-1:*"
    - Effect: Allow
      Action:
        - "cognito-idp:*"
      Resource:
        - "arn:aws:cognito-idp:us-east-1:*"

custom:
  stage: ${opt:stage, self:provider.stage}
  DB_PREFIX: ${self:service}-${file(./config.yml):${self:custom.stage}.DB_PREFIX}
  COGNITO_POOL_ID: ${file(./config.yml):${self:custom.stage}.COGNITO_POOL_ID}
  webpackIncludeModules: true
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${file(fixtures/migrations/family.yml):Properties.TableName}
            sources: [./fixtures/offline-seeds/family.json]
          - table: ${file(fixtures/migrations/family-user.yml):Properties.TableName}
            sources: [./fixtures/offline-seeds/family-user.json]
          - table: ${file(fixtures/migrations/job.yml):Properties.TableName}
            sources: [./fixtures/offline-seeds/job.json]
#  serverless-mocha-plugin:
#    preTestCommands:
#      - bash ./test/support/startOffline.sh
#    postTestCommands:
#      - bash ./test/support/stopOffline.sh
  # capacities:
  #   - table: ${self:custom.DB_PREFIX}-todos
  #     read:
  #       minimum: 5        # Minimum read capacity
  #       maximum: 1000     # Maximum read capacity
  #       usage: 0.75       # Targeted usage percentage
  #     write:
  #       minimum: 40       # Minimum write capacity
  #       maximum: 200      # Maximum write capacity
  #       usage: 0.5        # Targeted usage percentage

functions:
  checkHealth:
    handler: src/handlers/misc.health
    events:
      - http:
          method: GET
          path: health
          cors: true
          #authorizer: aws_iam
  getMe:
    handler: src/handlers/user.getMe
    events:
      - http:
          method: GET
          path: user/me
          cors: true
          authorizer:
            name: authorizer
            arn: ${file(./config.yml):${self:custom.stage}.COGNITO_POOL_ARN}
  listJobsByFamilyMember:
    handler: src/handlers/user.listJobs
    events:
      - http:
          method: POST
          path: user/me/jobs/{familyId}
          cors: true
          authorizer:
            name: authorizer
            arn: ${file(./config.yml):${self:custom.stage}.COGNITO_POOL_ARN}
      - http:
          method: POST
          path: user/{userId}/jobs/{familyId}
          cors: true
          authorizer:
            name: authorizer
            arn: ${file(./config.yml):${self:custom.stage}.COGNITO_POOL_ARN}
  getFamily:
    handler: src/handlers/family.get
    events:
      - http:
          method: GET
          path: family/{familyId}
          cors: true
          authorizer:
            name: authorizer
            arn: ${file(./config.yml):${self:custom.stage}.COGNITO_POOL_ARN}
  createFamily:
    handler: src/handlers/family.create
    events:
      - http:
          method: POST
          path: family
          cors: true
          authorizer:
            name: authorizer
            arn: ${file(./config.yml):${self:custom.stage}.COGNITO_POOL_ARN}
  joinFamily:
    handler: src/handlers/family.join
    events:
      - http:
          method: POST
          path: family/join
          cors: true
          authorizer:
            name: authorizer
            arn: ${file(./config.yml):${self:custom.stage}.COGNITO_POOL_ARN}
  listJobsByFamily:
    handler: src/handlers/family.listJobs
    events:
      - http:
          method: POST
          path: family/{familyId}/jobs
          cors: true
          authorizer:
            name: authorizer
            arn: ${file(./config.yml):${self:custom.stage}.COGNITO_POOL_ARN}
  preSignup:
    handler: src/handlers/signup.preSignup
    events:
      - cognitoUserPool:
          pool: PennyboxAppUsers-${self:custom.stage}
          trigger: PreSignUp
          timeout: 5

  postConfirmation:
    handler: src/handlers/signup.postConfirmation
    events:
      - cognitoUserPool:
          pool: PennyboxAppUsers-${self:custom.stage}
          trigger: PostConfirmation
  getJob:
    handler: src/handlers/job.get
    events:
      - http:
          method: GET
          path: job/{jobId}
          cors: true
          authorizer:
            name: authorizer
            arn: ${file(./config.yml):${self:custom.stage}.COGNITO_POOL_ARN}
  createJob:
    handler: src/handlers/job.create
    events:
      - http:
          method: POST
          path: job
          cors: true
          authorizer:
            name: authorizer
            arn: ${file(./config.yml):${self:custom.stage}.COGNITO_POOL_ARN}
  updateJobStatus:
    handler: src/handlers/job.updateStatus
    events:
      - http:
          method: PUT
          path: job/{jobId}/status
          cors: true
          authorizer:
            name: authorizer
            arn: ${file(./config.yml):${self:custom.stage}.COGNITO_POOL_ARN}

# you can add CloudFormation resource templates here
# resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
resources:
  Resources:
    familyTable: ${file(fixtures/migrations/family.yml)}
    familyUserTable: ${file(fixtures/migrations/family-user.yml)}
    jobTable: ${file(fixtures/migrations/job.yml)}
